vid: sharedcontent_reason
name: 'Shared Content Reason'
description: 'Reasons for why a Shared Content index does exists. Can be used for entity access.'
hierarchy: false
weight: 0
status: true
langcode: und
